/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_spark_gpu_simple_JNIInterface */

#ifndef _Included_com_ibm_spark_gpu_simple_JNIInterface
#define _Included_com_ibm_spark_gpu_simple_JNIInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_spark_gpu_simple_JNIInterface
 * Method:    incrementArrayValues
 * Signature: (I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_ibm_spark_gpu_simple_JNIInterface_incrementArrayValues
  (JNIEnv *, jobject, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
